# Generated by Django 3.1.4 on 2020-12-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_transport', models.CharField(max_length=64, verbose_name='TypeOfTransport')),
                ('cost_road', models.IntegerField(verbose_name='RoadCost')),
                ('cost_housing', models.IntegerField(verbose_name='AccommodationCost')),
            ],
        ),
    ]
