# Generated by Django 3.1.4 on 2020-12-28 23:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201229_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('surname', models.CharField(max_length=64, verbose_name='Surname')),
                ('last_name', models.CharField(max_length=64, verbose_name='Last name')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryPromotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name status')),
                ('date_up', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('num_of_workday', models.IntegerField(verbose_name='Number of workdays')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('det_per_hour', models.IntegerField(verbose_name='Detail per hour')),
                ('amount_h', models.IntegerField(verbose_name='Amount hour')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingMachine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name machine')),
                ('model', models.CharField(max_length=64, verbose_name='Model machine')),
                ('year_creation', models.IntegerField(verbose_name='Year creation')),
            ],
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={},
        ),
        migrations.AddField(
            model_name='hospitaltrip',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaltrip',
            name='disease',
            field=models.CharField(default='flu', max_length=64, verbose_name='Disease'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaltrip',
            name='num_days',
            field=models.IntegerField(default=10, verbose_name='Amount of days'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cost_housing',
            field=models.IntegerField(verbose_name='Price of housing'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='cost_road',
            field=models.IntegerField(verbose_name='Price of road'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type_of_transport',
            field=models.CharField(max_length=64, verbose_name='Type of transport'),
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Date start')),
                ('num_days', models.IntegerField(verbose_name='Amount of days')),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date of trip')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('num_days', models.IntegerField(verbose_name='Amount of days')),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('id_talon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coupon')),
            ],
        ),
        migrations.CreateModel(
            name='TableSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhd', models.IntegerField(verbose_name='Amount of hospital days')),
                ('ntd', models.IntegerField(verbose_name='Amount of trip days')),
                ('nvd', models.IntegerField(verbose_name='Amount of vacation days')),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employer')),
                ('id_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.month')),
            ],
        ),
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name subdivision')),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='PositionEm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('date_up', models.DateField()),
                ('id_rate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productionrate')),
            ],
        ),
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_oil', models.IntegerField(verbose_name='Year creation')),
                ('date_change', models.DateField()),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workingmachine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineBreakdowns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_breakdown', models.DateField()),
                ('num_breakdown', models.IntegerField(verbose_name='Number breakdowns')),
                ('cost', models.IntegerField(verbose_name='Costs')),
                ('id_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.workingmachine')),
            ],
        ),
        migrations.AddField(
            model_name='employer',
            name='id_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.positionem'),
        ),
        migrations.AddField(
            model_name='employer',
            name='id_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.historypromotions'),
        ),
        migrations.AddField(
            model_name='employer',
            name='id_subdivision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subdivision'),
        ),
        migrations.AlterField(
            model_name='hospitaltrip',
            name='id_employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.employer'),
        ),
    ]
